global using BlazorModel.Data;
global using BlazorModel.ViewModels;
global using BlazorWeb;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using BlazorWeb.Services.StudentService;
global using BlazorWeb.Extension;
global using System.Net.Http.Json;
global using BlazorStrap;